/* 
Photography Business Analysis: Data Cleaning - Project Sites Table
Author: Oliverius, Miranda
*/
 

/* When reviewing this table, there were a number of addresses that showed up multiple times. Duplicate addresses 
are only valid if they pertain to unique units (specified in the address_2 field) for the same street address or 
if unique clients have ordered a photoshoot for the same address (happens when a new agent takes over an address 
or if the same property is sold at a later date by another agent). In both of these instances, valid unique site 
IDs will appear in the orders table.

Invalid duplicates occur in cases where the address, address_2, and client_id fields are the same, but there are 
multiple site IDs. Most often, the additional site IDs are generated by the client portal, but only one site ID 
appears in the orders table for each address. To remedy the effects of these invalid duplicate project sites, 
records in the project_sites table will be removed if the address shows up more than once AND the site ID is not 
included in the orders table.

Any remaining duplicate entries for which address, address_2, and client_id are the same, but for which all site IDs 
are attached to an order ID require additional cleaning. For this scenario, the orders table will be updated so that 
only one site ID is used for all related orders. Then, the duplicate records in the project_sites table will be removed.
*/


-- view addresses that show up multiple times in the project_sites table
SELECT *
FROM project_sites
WHERE address IN (
	SELECT address
	FROM project_sites
	GROUP BY address
	HAVING COUNT(address) > 1
)
ORDER BY address;

/* delete duplicate project sites if the address shows up more than once but the site ID is not included in
the orders table
*/
DELETE FROM project_sites
WHERE address IN (
    SELECT address
    FROM project_sites
    GROUP BY address
    HAVING COUNT(address) > 1
) AND
site_id NOT IN (
    SELECT site_id
    FROM orders
);

-- check for any remaining addresses that show up multiple times in the project_sites table
SELECT *
FROM project_sites
WHERE address IN (
	SELECT address
	FROM project_sites
	GROUP BY address
	HAVING COUNT(address) > 1
)
ORDER BY address;

/* update orders table to use one single site_id in the orders table if address, address_2, and client_id 
are the same
*/
UPDATE orders
SET site_id = CASE
	WHEN site_id = '1397777' THEN '1336270'
	WHEN site_id = '1349701' THEN '1281248'
	ELSE site_id
END;

/* delete remaining duplicate project sites if the address shows up more than once but the site ID is not 
included in the orders table
*/
DELETE FROM project_sites
WHERE address IN (
    SELECT address
    FROM project_sites
    GROUP BY address
    HAVING COUNT(address) > 1
) AND
site_id NOT IN (
    SELECT site_id
    FROM orders
);